--- 模拟限流
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Issac.
--- DateTime: 2021/1/5 上午8:47
---

-- 用作限流的key
local key = 'My Key'

-- 限流最大阈值
local limit = 2

-- 当前流量大小
local currentLimit = 3

if currentLimit + 1 > limit then
    print 'reject'
    return false
else
    print 'accept'
    return true
end