---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Issac.
--- DateTime: 2021/1/6 上午8:00
---

-- 获取方法签名特征
local method = KEYS[1]
redis.log(redis.LOG_DEBUG, 'key is ',method)

-- 调用脚本传入的限流大小
local limit = tonumber(ARGV[1])

-- 获取当前流量大小
local count = tonumber(redis.call('get',method) or '0')

-- 是否超过限流阈值
if count + 1 > limit then
    -- 拒绝服务访问
    return false
else
    -- 没有超过阈值
    redis.call("INCRBY",method,1)
    -- 设置过期时间
    redis.call("EXPIRE",method,1)
    return true
end