server:
  port: 8002

spring:
  datasource:
    # 注册数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.106:3306/foodie-shop-dev?useUnicode=true&&characterEncoding=utf8
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接超时时长
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长，超时则被释放
      pool-name: DataSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长，超时而没被使用则被释放
      connection-test-query: SELECT 1
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 表示消费者成功消费消息需要手工签收
        acknowledge-mode: manual
        concurrency: 5
        prefetch: 1
        max-concurrency: 10
      order:
        exchange:
          name: exchange-1
          durable: true
          type: topic
          key: springboot.*
  kafka:
    bootstrap-servers: 192.168.1.104:9092
    consumer:
      # 关闭自动签收
      enable-auto-commit: false
      # 消费进度
      # latest 消费这从最新记录开始读取数据
      # earliest 从起始位置
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 手工签收
      ack-mode: manual
      concurrency: 5