server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/foodie-shop-dev?useUnicode=true&&characterEncoding=utf8
    password: root
  redis:
    # redis 单机单实例
    #    database: 1
    #    host: 192.168.1.106
    #    port: 6379
    #    password: issac
    # 哨兵模式
    database: 1
    password: issac
    sentinel:
      master: issac-master
      nodes: 192.168.1.106:26379,192.168.1.107:26379,192.168.1.108:26379
    # 集群模式
  #    password: issac
  #    cluster:
  #      nodes: 192.168.1.106:6379,192.168.1.107:6379,192.168.1.108:6379
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl