server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  datasource:
    # 注册数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///foodie-shop-dev?useUnicode=true
    username: root
    password: rootroot
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接超时时长
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长，超时则被释放
      pool-name: DataSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长，超时而没被使用则被释放
      connection-test-query: SELECT 1

# mybatis
mybatis:
  type-aliases-package: com.issac.pojo # pojo包路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis mapper 通用mapper设置
mapper:
  mappers: com.issac.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
